/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import * as runtime from '../runtime'
import type { HTTPValidationError } from '../models'
import { HTTPValidationErrorFromJSON, HTTPValidationErrorToJSON } from '../models'

export interface HandlerRequest {
    fullPath: string
}

/**
 *
 */
export class ApplicationApi extends runtime.BaseAPI {
    /**
     * Handler
     */
    async handlerRaw(
        requestParameters: HandlerRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<runtime.ApiResponse<any>> {
        if (requestParameters.fullPath === null || requestParameters.fullPath === undefined) {
            throw new runtime.RequiredError(
                'fullPath',
                'Required parameter requestParameters.fullPath was null or undefined when calling handler.',
            )
        }

        const queryParameters: any = {}

        const headerParameters: runtime.HTTPHeaders = {}

        const response = await this.request(
            {
                path: `/app/{full_path}`.replace(
                    `{${'full_path'}}`,
                    encodeURIComponent(String(requestParameters.fullPath)),
                ),
                method: 'GET',
                headers: headerParameters,
                query: queryParameters,
            },
            initOverrides,
        )

        return new runtime.TextApiResponse(response) as any
    }

    /**
     * Handler
     */
    async handler(
        requestParameters: HandlerRequest,
        initOverrides?: RequestInit | runtime.InitOverrideFunction,
    ): Promise<any> {
        const response = await this.handlerRaw(requestParameters, initOverrides)
        return await response.value()
    }
}
