/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface BaseResponseModel
 */
export interface BaseResponseModel {
    /**
     *
     * @type {string}
     * @memberof BaseResponseModel
     */
    status: string
    /**
     *
     * @type {string}
     * @memberof BaseResponseModel
     */
    message?: string
    /**
     *
     * @type {any}
     * @memberof BaseResponseModel
     */
    data?: any | null
}

/**
 * Check if a given object implements the BaseResponseModel interface.
 */
export function instanceOfBaseResponseModel(value: object): boolean {
    let isInstance = true
    isInstance = isInstance && 'status' in value

    return isInstance
}

export function BaseResponseModelFromJSON(json: any): BaseResponseModel {
    return BaseResponseModelFromJSONTyped(json, false)
}

export function BaseResponseModelFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): BaseResponseModel {
    if (json === undefined || json === null) {
        return json
    }
    return {
        status: json['status'],
        message: !exists(json, 'message') ? undefined : json['message'],
        data: !exists(json, 'data') ? undefined : json['data'],
    }
}

export function BaseResponseModelToJSON(value?: BaseResponseModel | null): any {
    if (value === undefined) {
        return undefined
    }
    if (value === null) {
        return null
    }
    return {
        status: value.status,
        message: value.message,
        data: value.data,
    }
}
