/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ImageGenerationError
 */
export interface ImageGenerationError {
    /**
     * 
     * @type {string}
     * @memberof ImageGenerationError
     */
    type?: ImageGenerationErrorTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ImageGenerationError
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof ImageGenerationError
     */
    message: string;
}


/**
 * @export
 */
export const ImageGenerationErrorTypeEnum = {
    error: 'error'
} as const;
export type ImageGenerationErrorTypeEnum = typeof ImageGenerationErrorTypeEnum[keyof typeof ImageGenerationErrorTypeEnum];


/**
 * Check if a given object implements the ImageGenerationError interface.
 */
export function instanceOfImageGenerationError(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;

    return isInstance;
}

export function ImageGenerationErrorFromJSON(json: any): ImageGenerationError {
    return ImageGenerationErrorFromJSONTyped(json, false);
}

export function ImageGenerationErrorFromJSONTyped(json: any, ignoreDiscriminator: boolean): ImageGenerationError {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'error': !exists(json, 'error') ? undefined : json['error'],
        'message': json['message'],
    };
}

export function ImageGenerationErrorToJSON(value?: ImageGenerationError | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'error': value.error,
        'message': value.message,
    };
}

