/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface ModelCurrentResponseModel
 */
export interface ModelCurrentResponseModel {
    /**
     * 
     * @type {string}
     * @memberof ModelCurrentResponseModel
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof ModelCurrentResponseModel
     */
    message?: string;
    /**
     * 
     * @type {string}
     * @memberof ModelCurrentResponseModel
     */
    data?: string;
}

/**
 * Check if a given object implements the ModelCurrentResponseModel interface.
 */
export function instanceOfModelCurrentResponseModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;

    return isInstance;
}

export function ModelCurrentResponseModelFromJSON(json: any): ModelCurrentResponseModel {
    return ModelCurrentResponseModelFromJSONTyped(json, false);
}

export function ModelCurrentResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): ModelCurrentResponseModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : json['data'],
    };
}

export function ModelCurrentResponseModelToJSON(value?: ModelCurrentResponseModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'message': value.message,
        'data': value.data,
    };
}

