/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
import type { PluginData } from './PluginData'
import { PluginDataFromJSON, PluginDataFromJSONTyped, PluginDataToJSON } from './PluginData'

/**
 *
 * @export
 * @interface PluginListResponseModel
 */
export interface PluginListResponseModel {
    /**
     *
     * @type {string}
     * @memberof PluginListResponseModel
     */
    status: string
    /**
     *
     * @type {string}
     * @memberof PluginListResponseModel
     */
    message?: string
    /**
     *
     * @type {Array<PluginData>}
     * @memberof PluginListResponseModel
     */
    data: Array<PluginData>
}

/**
 * Check if a given object implements the PluginListResponseModel interface.
 */
export function instanceOfPluginListResponseModel(value: object): boolean {
    let isInstance = true
    isInstance = isInstance && 'status' in value
    isInstance = isInstance && 'data' in value

    return isInstance
}

export function PluginListResponseModelFromJSON(json: any): PluginListResponseModel {
    return PluginListResponseModelFromJSONTyped(json, false)
}

export function PluginListResponseModelFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): PluginListResponseModel {
    if (json === undefined || json === null) {
        return json
    }
    return {
        status: json['status'],
        message: !exists(json, 'message') ? undefined : json['message'],
        data: (json['data'] as Array<any>).map(PluginDataFromJSON),
    }
}

export function PluginListResponseModelToJSON(value?: PluginListResponseModel | null): any {
    if (value === undefined) {
        return undefined
    }
    if (value === null) {
        return null
    }
    return {
        status: value.status,
        message: value.message,
        data: (value.data as Array<any>).map(PluginDataToJSON),
    }
}
