/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
import type { BuildEngineError } from './BuildEngineError';
import {
    BuildEngineErrorFromJSON,
    BuildEngineErrorFromJSONTyped,
    BuildEngineErrorToJSON,
} from './BuildEngineError';
import type { BuildEngineProgress } from './BuildEngineProgress';
import {
    BuildEngineProgressFromJSON,
    BuildEngineProgressFromJSONTyped,
    BuildEngineProgressToJSON,
} from './BuildEngineProgress';

/**
 * 
 * @export
 * @interface ResponseBuildEngine
 */
export interface ResponseBuildEngine {
    /**
     * 
     * @type {string}
     * @memberof ResponseBuildEngine
     */
    type?: ResponseBuildEngineTypeEnum;
    /**
     * 
     * @type {string}
     * @memberof ResponseBuildEngine
     */
    error?: string;
    /**
     * 
     * @type {string}
     * @memberof ResponseBuildEngine
     */
    message: string;
    /**
     * 
     * @type {number}
     * @memberof ResponseBuildEngine
     */
    progress: number;
}


/**
 * @export
 */
export const ResponseBuildEngineTypeEnum = {
    result: 'result'
} as const;
export type ResponseBuildEngineTypeEnum = typeof ResponseBuildEngineTypeEnum[keyof typeof ResponseBuildEngineTypeEnum];


/**
 * Check if a given object implements the ResponseBuildEngine interface.
 */
export function instanceOfResponseBuildEngine(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "message" in value;
    isInstance = isInstance && "progress" in value;

    return isInstance;
}

export function ResponseBuildEngineFromJSON(json: any): ResponseBuildEngine {
    return ResponseBuildEngineFromJSONTyped(json, false);
}

export function ResponseBuildEngineFromJSONTyped(json: any, ignoreDiscriminator: boolean): ResponseBuildEngine {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'type': !exists(json, 'type') ? undefined : json['type'],
        'error': !exists(json, 'error') ? undefined : json['error'],
        'message': json['message'],
        'progress': json['progress'],
    };
}

export function ResponseBuildEngineToJSON(value?: ResponseBuildEngine | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'type': value.type,
        'error': value.error,
        'message': value.message,
        'progress': value.progress,
    };
}

