/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface SetModeRequest
 */
export interface SetModeRequest {
    /**
     *
     * @type {string}
     * @memberof SetModeRequest
     */
    mode: SetModeRequestModeEnum
}

/**
 * @export
 */
export const SetModeRequestModeEnum = {
    diffusers: 'diffusers',
    tensorrt: 'tensorrt',
} as const
export type SetModeRequestModeEnum =
    (typeof SetModeRequestModeEnum)[keyof typeof SetModeRequestModeEnum]

/**
 * Check if a given object implements the SetModeRequest interface.
 */
export function instanceOfSetModeRequest(value: object): boolean {
    let isInstance = true
    isInstance = isInstance && 'mode' in value

    return isInstance
}

export function SetModeRequestFromJSON(json: any): SetModeRequest {
    return SetModeRequestFromJSONTyped(json, false)
}

export function SetModeRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): SetModeRequest {
    if (json === undefined || json === null) {
        return json
    }
    return {
        mode: json['mode'],
    }
}

export function SetModeRequestToJSON(value?: SetModeRequest | null): any {
    if (value === undefined) {
        return undefined
    }
    if (value === null) {
        return null
    }
    return {
        mode: value.mode,
    }
}
