/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime'
/**
 *
 * @export
 * @interface SetModelRequest
 */
export interface SetModelRequest {
    /**
     *
     * @type {string}
     * @memberof SetModelRequest
     */
    model_id: string
}

/**
 * Check if a given object implements the SetModelRequest interface.
 */
export function instanceOfSetModelRequest(value: object): boolean {
    let isInstance = true
    isInstance = isInstance && 'model_id' in value

    return isInstance
}

export function SetModelRequestFromJSON(json: any): SetModelRequest {
    return SetModelRequestFromJSONTyped(json, false)
}

export function SetModelRequestFromJSONTyped(
    json: any,
    ignoreDiscriminator: boolean,
): SetModelRequest {
    if (json === undefined || json === null) {
        return json
    }
    return {
        model_id: json['model_id'],
    }
}

export function SetModelRequestToJSON(value?: SetModelRequest | null): any {
    if (value === undefined) {
        return undefined
    }
    if (value === null) {
        return null
    }
    return {
        model_id: value.model_id,
    }
}
