/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface SetRunnerRequest
 */
export interface SetRunnerRequest {
    /**
     * 
     * @type {string}
     * @memberof SetRunnerRequest
     */
    model_id: string;
    /**
     * 
     * @type {string}
     * @memberof SetRunnerRequest
     */
    tokenizer_id?: string;
}

/**
 * Check if a given object implements the SetRunnerRequest interface.
 */
export function instanceOfSetRunnerRequest(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "model_id" in value;

    return isInstance;
}

export function SetRunnerRequestFromJSON(json: any): SetRunnerRequest {
    return SetRunnerRequestFromJSONTyped(json, false);
}

export function SetRunnerRequestFromJSONTyped(json: any, ignoreDiscriminator: boolean): SetRunnerRequest {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'model_id': json['model_id'],
        'tokenizer_id': !exists(json, 'tokenizer_id') ? undefined : json['tokenizer_id'],
    };
}

export function SetRunnerRequestToJSON(value?: SetRunnerRequest | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'model_id': value.model_id,
        'tokenizer_id': value.tokenizer_id,
    };
}

