/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FileListResponseModel
 */
export interface FileListResponseModel {
    /**
     * 
     * @type {string}
     * @memberof FileListResponseModel
     */
    status: string;
    /**
     * 
     * @type {string}
     * @memberof FileListResponseModel
     */
    message?: string;
    /**
     * 
     * @type {{ [key: string]: object; }}
     * @memberof FileListResponseModel
     */
    data?: { [key: string]: object; };
    /**
     * 
     * @type {number}
     * @memberof FileListResponseModel
     */
    length: number;
}

/**
 * Check if a given object implements the FileListResponseModel interface.
 */
export function instanceOfFileListResponseModel(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "status" in value;
    isInstance = isInstance && "length" in value;

    return isInstance;
}

export function FileListResponseModelFromJSON(json: any): FileListResponseModel {
    return FileListResponseModelFromJSONTyped(json, false);
}

export function FileListResponseModelFromJSONTyped(json: any, ignoreDiscriminator: boolean): FileListResponseModel {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'status': json['status'],
        'message': !exists(json, 'message') ? undefined : json['message'],
        'data': !exists(json, 'data') ? undefined : json['data'],
        'length': json['length'],
    };
}

export function FileListResponseModelToJSON(value?: FileListResponseModel | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'status': value.status,
        'message': value.message,
        'data': value.data,
        'length': value.length,
    };
}

