/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { exists, mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface GenerateImageResponseData
 */
export interface GenerateImageResponseData {
    /**
     * 
     * @type {object}
     * @memberof GenerateImageResponseData
     */
    images: object;
    /**
     * 
     * @type {number}
     * @memberof GenerateImageResponseData
     */
    performance: number;
}

/**
 * Check if a given object implements the GenerateImageResponseData interface.
 */
export function instanceOfGenerateImageResponseData(value: object): boolean {
    let isInstance = true;
    isInstance = isInstance && "images" in value;
    isInstance = isInstance && "performance" in value;

    return isInstance;
}

export function GenerateImageResponseDataFromJSON(json: any): GenerateImageResponseData {
    return GenerateImageResponseDataFromJSONTyped(json, false);
}

export function GenerateImageResponseDataFromJSONTyped(json: any, ignoreDiscriminator: boolean): GenerateImageResponseData {
    if ((json === undefined) || (json === null)) {
        return json;
    }
    return {
        
        'images': json['images'],
        'performance': json['performance'],
    };
}

export function GenerateImageResponseDataToJSON(value?: GenerateImageResponseData | null): any {
    if (value === undefined) {
        return undefined;
    }
    if (value === null) {
        return null;
    }
    return {
        
        'images': value.images,
        'performance': value.performance,
    };
}

